### ISSUE TITLE
Conda package?

### ISSUE THREAD

**Issue by crbinz** [brandon-rhodes/python-sgp4#10]
Hi,

Not sure where else to ask about this, but here goes. I see that this package is listed on PyPI, but it would be useful for me to have it accessible with Conda (i.e. `conda install sgp4`) -- specifically, for my [Julia wrapper](https://github.com/crbinz/SGP4.jl) of this package. Apparently there is a way to do this, but it requires that someone hosts the Conda package once it's created.

I am happy to try and figure this out and host it, but it's not clear to me that you (as the original author) or this Github repository is clearly indicated once it's hosted on the "Anaconda cloud" (formerly binstar, I think?). So, I figured I'd give you the chance to do it yourself, if you'd like. Thanks, either way.

Chris

**Comment by brandon-rhodes** [comment]
Alas, I do not currently have the cycles to support an alternative packager. My own current practice is to just `pip` install into my Anaconda environment anything I need that doesn't come from conda itself. :) So please feel free to do so yourself — and thanks for asking first!

**Comment by crbinz** [comment]
Completely understand. I'm still trying to figure out the best solution for my problem, so I may or may not host the conda package.

**Comment by Juanlu001** [comment]
Did I hear "conda"? :smile:

**Comment by Juanlu001** [comment]
All right, I'm already hosting sgp4 conda packages in this channel:

https://anaconda.org/poliastro/sgp4

using the recipe in #13. They should be easy to install using `conda install sgp4 --channel poliastro`.
