### ISSUE TITLE
How calc satellite swath?

### ISSUE THREAD

**Issue by ahvahsky2008** [brandon-rhodes/python-sgp4#106]
Hi. Hos calc satellite swath? 
![image](https://user-images.githubusercontent.com/8035828/180880663-29a5cd65-83a1-4933-8cb8-9e86ff9dcf88.png)

**Comment by brandon-rhodes** [comment]
I am not sure how to calculate swath. This `sgp4` library mere wraps the routines offered by the official `SGP4.cpp` library, alas, it does not add any new ones like swatch calculation.
