### ISSUE TITLE
Vallado cpp license

### ISSUE THREAD

**Issue by mattiaverga** [brandon-rhodes/python-sgp4#112]
python-sgp4 README file should add a citation and a link to upstream Vallado code, as required in [upstream FAQ](https://celestrak.org/publications/AIAA/2006-6753/faq.php):

> **Are there any Licenses required to use the SGP4 code?**
> There is no license associated with the code and you may use it for any purpose—personal or commercial—as you wish. We ask only that you include citations in your documentation and source code to show the source of the code and provide links to the [main page](https://celestrak.org/publications/AIAA/2006-6753/), to facilitate communications regarding any questions on the theory or source code.

**Comment by brandon-rhodes** [comment]
The README links to the `Documentation` at https://pypi.python.org/pypi/sgp4/ which includes a link to https://www.celestrak.com/publications/AIAA/2006-6753/ — do you think the link is at the proper position on the page, or do you think a second link should be added, up at the top so it's easier to find?

**Comment by mattiaverga** [comment]
The link to upstream original sources seems a bit buried, maybe a README under the `extension` directory explaining where the .cpp and .h code is from would be easier to find. Or a paragraph in the main README.

**Comment by brandon-rhodes** [comment]
The next version's docs will link to the Spacetrak Report right in the first sentence of the docs. Thanks for the idea!
