### ISSUE TITLE
Accessing the version number from inside Python

### ISSUE THREAD

**Issue by xvii-Dietrich** [brandon-rhodes/python-sgp4#113]
I am unable to find a method for checking the version of python-sgp4 within the code itself. In many other packages, there is either a function or a local variable that will give the version number of the installed package. To give an example from another package: 

```
import astropy; print (astropy.__version__)
import numpy;print (numpy.__version__)
```
Those work. However:
```
import sgp4;print(sgp4.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sgp4' has no attribute '__version__'
```
The motivation for doing this is to enable internal unit testing, which is part of the regression testing/checking that is done as part of routine software builds. It also assists in the validation testing for remote installations (especially when being done within controlled container/conda type environments).

If not adding the `__version__` variable, then please document a way to do this in the online notes. Thanks!

**Comment by brandon-rhodes** [comment]
When I try your code, I see this printed to the screen:

    2.21

Could you check the content of the `sgp4/__init__.py` file? It should have the version at the bottom; or, failing that, a changelog just above it, and maybe you could find the version visually from that to let us know which version you have installed. It looks like it was only added in 2.20, so maybe you're still on 1.19 or earlier.

**Comment by xvii-Dietrich** [comment]
Thanks for the super-fast response. Yes, you're right, I' was on an old version.

According to `~/.local/lib/python3.6/site-packages/sgp4/__init__.py`, I had:
```
Changelog
---------
| 2021-04-22 — 2.19
* Extended the documentation on the Python Package Index and in the
  module docstring so it lists every ``Satrec`` attribute that this
  library exposes; even the more obscure ones might be useful to folks
  working to analyze satellite orbits.
```
So, I was a couple of versions behind, and the problem is already solved - so it was a non-issue. I've upgraded and it is indeed already now fixed. Thanks!

Some further notes... in case it helps anyone else:

- One can check _all_ the installed packages with `pip3 list`
- One can search for outdated packages with `pip3 list --outdated`
- SGP4 can be updated to the latest version with `pip3 install --user --upgrade sgp4`

**Comment by brandon-rhodes** [comment]
Thanks for the quick follow-up — I previously had to pipe `pip freeze` into `grep` to find a version number, I had not tried out their `list` subcommand!
