### ISSUE TITLE
Error code 1 despite satellite.ecco having a value between 0 and 1.

### ISSUE THREAD

**Issue by kawsarshirazul** [brandon-rhodes/python-sgp4#130]
I am trying to get the location, `r`, for a satellite by providing a TLE to the `Satrec.twoline2rv` function from the `sgp4.api`.

The TLE is obtained using the space-track.org API, and the below request URL.
https://www.space-track.org/basicspacedata/query/class/gp_history/epoch/2022-03-28~~/norad_cat_id/26463/predicates/object_name,norad_cat_id,epoch,tle_line1,tle_line2/format/html

The Python code is below. It returns null `r` values, and an error code of 1 suggesting that the eccentricity is not between 0 and 1. However, `C1.ecco` returns an eccentricity of 0.6613884.

Thanks in advance.

```
tle_line1 = "1 26463U 00045A 15061.55382988 .00000103 00000-0 00000+0 0 9994"
tle_line2 = "2 26463 139.1946 350.2185 6613884 203.1366 0.5457 0.44214876 25797"

C1 = Satrec.twoline2rv(tle_line1, tle_line2)
jd, fr = jday(2022, 3, 28, 11, 28, 34.215)
e, r, v = C1.sgp4(jd, fr).```

**Comment by brandon-rhodes** [comment]
I don't get an error when I run that script. Could you check the SGP4 lines? It looks like there are missing spaces. Here's how you can verify that those TLE lines have broken formatting:

https://pypi.org/project/sgp4/#double-checking-your-tle-lines

**Comment by kawsarshirazul** [comment]
Problem solved, thank you very much.

However, I would also like to note that while adding spaces was the solution to the issue, I didn't need to replicate the exact format from the punch cards described by `twoline2rv()`'s raised error. Just adding an extra two spaces to `tle_line1` between the third field (00045A) and the fourth field (15061.55382988) was enough. Why is that?

**Comment by brandon-rhodes** [comment]
My guess is that the TLE routine ignores the final numbers on Line 1, and instead pays attention to the numbers on Line 2. Thanks for following up so that I can close the issue!
