### ISSUE TITLE
Acceptable API breakage to support Numba acceleration?

### ISSUE THREAD

**Issue by ckuethe** [brandon-rhodes/python-sgp4#14]
While investigating https://github.com/skyfielders/python-skyfield/issues/30 I found a few places where an API break would be necessary to fully accelerate the function. In particular, passing in a string as a flag and comparing it to a constant eg. [_dpper](https://github.com/brandon-rhodes/python-sgp4/blob/master/sgp4/propagation.py#L272) does not optimize well. Potentially better results could be obtained by using integer or boolean parameters.

Also, Numba [doesn't support try-except in jitted code](https://github.com/numba/numba/issues/1679). That might not be a big problem if sgp4 is compiled early rather than lazy, since numba is only needed at build time and not runtime. That may also save some of the horrible compilation time.

Thoughts?

**Comment by brandon-rhodes** [comment]
I would be very happy to see the string constants replaced with integers. We can always use symbols for them, so that `opsmode == 'a'` would become `opsmode == AFSPC` or something.

Which examples of try-except are you thinking you could change or remove that might make the routines easier for Numba to optimize?

**Comment by ckuethe** [comment]
```opsmode``` can probably go away entirely. The user only sees a boolean ```afspc_mode```  and and only if they know to go looking for it. In my tree I modified ```sgp4init``` to use ```afspc_mode``` directly.

[twoline2rv](https://github.com/brandon-rhodes/python-sgp4/blob/master/sgp4/io.py#L130) has a couple of try-except blocks.  It would be easy enough to change all those asserts into one big test, which would raise the same exception if any of the format checks failed.

**Comment by ckuethe** [comment]
https://github.com/brandon-rhodes/python-sgp4/pull/15 gets rid of ```opsmode```
https://github.com/brandon-rhodes/python-sgp4/pull/16 removes the try-except.

**Comment by Juanlu001** [comment]
Status update: any reason #15 was closed @ckuethe? :)

**Comment by brandon-rhodes** [comment]
My guess is that I took far too long to review it and he wanted it off of his GitHub dashboard. I am still ramping back up my open source involvement following PyCon, but I'll try putting this closer to the top of my list and see if I can get sgp4 issues and pull requests moving again!

**Comment by brandon-rhodes** [comment]
@ckuethe @Juanlu001 I re-opened and merged the pull request. Thanks very much, @ckuethe, for this work, and hopefully we'll soon be delivering a faster experience with this library — should we now think about adding a routine to speed things up with Numba if possible?

**Comment by Juanlu001** [comment]
What about having numba as an optional dependency and doing something like this?

https://github.com/poliastro/poliastro/blob/v0.6.0/src/poliastro/jit.py

**Comment by ckuethe** [comment]
@Juanlu001 - I think I closed it because a similar change was part of another PR that had been merged. Or that's what it looked like to me.

**Comment by ckuethe** [comment]
@brandon-rhodes yeah, I was getting bored of waiting for reviews. I'm spending a lot of time on aircraft and in waiting rooms this week; perhaps I'll have some time to restart my skyfield tinkering with the goal of getting it to run under micropython on an esp8266.

**Comment by brandon-rhodes** [comment]
Wow, micropython! Let us know how it goes, and hopefully you will find me responsive from now on.

**Comment by ckuethe** [comment]
It's worth calling attention to these two bits of numba documentation.

* http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#numba-troubleshooting
* http://numba.pydata.org/numba-doc/latest/user/jit.html#nopython

It is recommended to only compile critical paths (profiling says that `_dpper` would be appropriate) and that `nopython` mode is probably desirable for development so that compilation will hard fail rather than producing slow python objects which basically provide no speedup - I probably wouldn't inflict that runtime failure case on users though, but I have a feeling (hypothesis is too well formed) that this might lead to better code even in the fake-jit case such as micropython.

**Comment by Juanlu001** [comment]
I guess this can be closed? :)

**Comment by brandon-rhodes** [comment]
I think we should wait before closing it until someone adds Numba acceleration, because I think it's very important for many sgp4 use cases. I'm happy to leave issues open indefinitely, even for projects without many volunteers, so I have no problem leaving this open! Thanks for checking in, though.

**Comment by Juanlu001** [comment]
Oops, sorry! I misunderstood after seeing that https://github.com/brandon-rhodes/python-sgp4/pull/17 was merged.

**Comment by brandon-rhodes** [comment]
I haven't had time to dig in and learn whether #17 accomplishes all we could hope and dream for how SGP4 could be Numba-accelerated, so I don't know either way! Let's leave this issue open for folks to post their results as we learn.

**Comment by ckuethe** [comment]
As the author of #17, I am absolutely certain that it's not as good as it gets. I could do some more digging, but I'm not terribly enthusiastic about doing that work that if we're going to try keep the Fortran/C style.

**Comment by ckuethe** [comment]
Revisiting this a little with test program of a geostationary satellite.

with numba, cprofile says:
```
         8 function calls in 3.421 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    3.421    3.421 model.py:44(propagate)
        1    0.000    0.000    3.421    3.421 propagation.py:1640(sgp4)
        1    3.421    3.421    3.421    3.421 propagation.py:918(_dspace)
        1    0.000    0.000    0.000    0.000 {method 'format' of 'str' objects}
        1    0.000    0.000    0.000    0.000 ext.py:475(jday)
        2    0.000    0.000    0.000    0.000 {pow}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

without numba, cprofile says:
```
         210654697 function calls in 62.818 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   62.818   62.818 model.py:44(propagate)
        1    0.000    0.000   62.818   62.818 propagation.py:1645(sgp4)
        1   45.367   45.367   62.818   62.818 propagation.py:931(_dspace)
 90280581    7.791    0.000    7.791    0.000 {math.cos}
 90280581    7.740    0.000    7.740    0.000 {math.sin}
 30093527    1.920    0.000    1.920    0.000 {math.fabs}
        1    0.000    0.000    0.000    0.000 {method 'format' of 'str' objects}
        2    0.000    0.000    0.000    0.000 {pow}
        1    0.000    0.000    0.000    0.000 ext.py:473(jday)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

I did a rather ugly thing to `_dpper`, turning it into a wrapper for its real logic in _dpper_inner which then takes a bunch of scalar values rather than a `satrec`. This at least allows numba to compile it a bit, though I have not yet demonstrated a significant gain from doing so.

**Comment by brandon-rhodes** [comment]
Thanks for the work and ideas on this experiment, everyone! I have removed the Numba trial. Let’s instead focus on trying to keep the library's C++ acceleration compiled and available for all platforms — which, alas, might be a bigger problem than I had anticipated; just earlier this week, my second attempt to release with the new CI tooling resulted in no wheels for Mac.
