### ISSUE TITLE
io.py, 'TypeError: startswith first arg must be bytes or a tuple of bytes, not str'

### ISSUE THREAD

**Issue by ghost** [brandon-rhodes/python-sgp4#29]
Hello, this may be a fairly simple question, as I'm just starting Python, coming from Matlab, but here goes:

I get the error:

File "C:\ProgramData\Anaconda3\lib\site-packages\sgp4\io.py", line 131, in twoline2rv
    assert line.startswith('1 ')
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

When trying to run the code. I have tried to change the '1' in the startswith function to a different type by adding a b before the '1', by using bytes('1'), by using tuple('1'), and by using str.encode('1'), but I continue to get the exact same error.

Any ideas? Thanks!

**Comment by brandon-rhodes** [comment]
(I just saw this! I wonder why my GitHub notifications didn't show it to me 26 days ago?)

How did you open the file that you've passed in — and I'm surprised that `b'1 '` didn't solve the problem! Could you paste in the full traceback with it changed to `b` like this? Thanks!

**Comment by brandon-rhodes** [comment]
Also: it will help to see some example code that experiences this problem, and to see the full traceback.

**Comment by brandon-rhodes** [comment]
I'm going to close this temporarily to keep it off my dashboard, until you can provide more information. As soon as you do, we'll reopen it and get to the bottom of your problem!
