### ISSUE TITLE
Coordinate mismatch between PyEphem/SSCWeb and this library

### ISSUE THREAD

**Issue by letmaik** [brandon-rhodes/python-sgp4#3]
``` python
# TLE for ISS
t1 = '1 25544U 98067A   12035.27140256  .00008132  00000-0  10934-3 0  9453'
t2 = '2 25544 051.6417 073.7902 0020652 004.6179 085.0245 15.58669131757138'
tle = twoline2rv(t1, t2, wgs72)
position, _ = tle.propagate(2012,2,4,7,55,00)
print position
# (-2395.0416350887344, 4440.7514261050846, 4492.3844513630256)
```

When I use http://sscweb.gsfc.nasa.gov/ I get the following coordinates:
`-2377.74        4447.21        4495.19`

These agree with the ones I get when using PyEphem for the same data.

Any ideas?

**Comment by cnwangfeng** [comment]
Dear brandon, I also met the issue of neothemachine. I do need a conversion from X,Y,Z to J2000. I try to read your codes in SKyfield. But it's a difficult job for me. May you tell me where I can find the code? I just download SGP4 new version. Quite good.

**Comment by cnwangfeng** [comment]
Brandon, I read the codes. Now I use SGP4 to obtain the vector value of ECEF. Am I right ? I then use NOVAS to transform to GCRS? However, I need the topocentric value . How can I do ?

**Comment by brandon-rhodes** [comment]
@cnwangfeng — what coordinate system are your x,y,z coordinates in?

**Comment by cnwangfeng** [comment]
I got X,Y,Z from SGP4. But I don't know the coordinate system of them? I guess it's ECEF? Am I right?

**Comment by brandon-rhodes** [comment]
Have you tried asking Skyfield to do the conversion? It uses SGP4 under the covers, but will do all of the conversions for you to either RA/dec or alt/az:

http://rhodesmill.org/skyfield/earth-satellites.html

**Comment by cnwangfeng** [comment]
Yes. I am reading the codes. I use JPL DE405 and NOVAS to calculate the position of planets in the solar system. I need the topocentric position (RA/DEC) of the target. In the following study, I have to calculate the satellite's topocentric position (RA/DEC). I just read the paper you suggested. the values outputted
by SGP4 is TEME coordinate? Not J2000?

**Comment by brandon-rhodes** [comment]
Yes, SGP4 outputs TEME coordinates.

**Comment by hshe824** [comment]
Hi there, does anyone know what the underlying mathematical/physical model that is being used to calculate the position of a Satellite from reading a TLE file in the compute() function in PyEphem is? Is it SGP4? Thanks

**Comment by brandon-rhodes** [comment]
Yes, it's SGP4, but an older version of the algorithm that sometimes crashes. Here's a publication that describes the various bugs that are found in older versions like PyEphem's:

https://celestrak.com/publications/AIAA/2006-6753/AIAA-2006-6753.pdf
