### ISSUE TITLE
`pip install` installs 2015 version of this library

### ISSUE THREAD

**Issue by rirze** [brandon-rhodes/python-sgp4#37]
Just wanted to raise this issue while it stands true. The version history on PyPi shows this: https://pypi.org/project/sgp4/#history

If the PyPi version could be updated, that would make it easier for others to use the latest improvements of this library. Thanks!

**Comment by brandon-rhodes** [comment]
Good idea! I hadn't stopped to notice how many tweaks had accumulated. (I release Skyfield more regularly, but apparently not the libraries behind it.)

**Comment by Juanlu001** [comment]
With the new 2.x releases I guess this can be closed :tada:
