### ISSUE TITLE
Documentation and changelog in README?

### ISSUE THREAD

**Issue by Juanlu001** [brandon-rhodes/python-sgp4#44]
> Yes, the documentation and changelog are here:
> 
> https://pypi.org/project/sgp4/
> 
> So that I can make the experience more convenient for users: where did you look that lacked a link to the documentation? I'll be happy to add more links to the docs to help folks find them!

_Originally posted by @brandon-rhodes in https://github.com/skyfielders/python-skyfield/issues/30#issuecomment-581403032_

**Comment by Juanlu001** [comment]
I initially looked at the README, then looked for `NEWS.txt`, or `CHANGELOG.md`, or `doc/`, then I went to https://github.com/brandon-rhodes/python-sgp4/releases, and then I admit I actually opened the PyPI page but didn't see the changelog.

However, I understand that you are putting all the relevant information in `sgp4` docstring and maintaining it in two places (there and the README) wouldn't be ideal.

**Comment by brandon-rhodes** [comment]
There, I've added an explicit link! Hopefully that will lead new folks directly to the information they need. Thanks for pointing out that it was hard to find.
