### ISSUE TITLE
2.0 jday returns incorrect result

### ISSUE THREAD

**Issue by interplanetarychris** [brandon-rhodes/python-sgp4#51]
The following function returns a fractional number (apparently ending in 0.5) for jd, which probably means that the fr is wrong too.

https://github.com/brandon-rhodes/python-sgp4/blob/2e1a06ff41122ba7d4ee6a3412788cd82455165b/sgp4/functions.py#L17-L21

Have a fix (based on ext.jday) in an incoming PR.

**Comment by brandon-rhodes** [comment]
Julian dates start at noon UTC, not midnight. Could that account for the 0.5 you are seeing?

**Comment by interplanetarychris** [comment]
Perhaps, but then explain why I need to handle the fractional part separately, and why 0.5 isn't part of that fraction per issue https://github.com/brandon-rhodes/python-sgp4/issues/53

**Comment by brandon-rhodes** [comment]
Let me know whether the new documentation has clarified how Julian dates work, or whether a bit more explanation should be added (or at least links to other resources) around the fact that Julian dates always have “.5” at the end because of the midnight-vs-noon thing. Thanks!

**Comment by interplanetarychris** [comment]
Understanding that it isn't meant to be an integer result, and in essence is an arbitrarily reduced version, allowing for a higher precision `0 < fr < 1` solution, I see that this is indeed working as intended.

**Comment by brandon-rhodes** [comment]
To help folks who read the function in the future, I have:

1. Extended the docstring with a doctest showing the 0.5 fraction.
2. Explained why the fraction arises.
3. Referred readers to Vallado's jday() function which returns the same pair of floats, including the 0.5 attached to the first one.

Let me know if you catch any typos in the docstring. Thanks!
