### ISSUE TITLE
Improper initialization of averaged mean element variables

### ISSUE THREAD

**Issue by interplanetarychris** [brandon-rhodes/python-sgp4#54]
I believe the following is a bug in the Vallado source code, when initializing `Satrec()` variables in `sgp4init()`:

https://github.com/brandon-rhodes/python-sgp4/blob/2a365a3bc8b2e2343a4efe3d611b89c971676870/extension/SGP4.cpp#L1449-L1450

These variables aren't used elsewhere within the code, so the fact that they all take the last-set value as follows doesn't cause any internal problems:

https://github.com/brandon-rhodes/python-sgp4/blob/2a365a3bc8b2e2343a4efe3d611b89c971676870/extension/SGP4.cpp#L1870

However, anyone accessing them externally (for example, to reset the epoch of the osculating elements) will find that they all equal `satrec.nm`

**Comment by brandon-rhodes** [comment]
I do not yet quite see, reading those two snippets of code, how all of those other values get set to `nm`. Could you share a small Python script that shows how the values are misbehaving, so that I have a test case of the everything-equal-to-`nm` behavior? Thanks!

**Comment by interplanetarychris** [comment]
Upon writing a test script, discovered it was a false alarm.

Noticing that the variables some come out different by 2*pi, given the differences in python %, and cmath fmod.
