### ISSUE TITLE
Language settings influence TLE two-line import

### ISSUE THREAD

**Issue by mworion** [brandon-rhodes/python-sgp4#63]
All versions run in accelerated mode (always True)
Situation could be replicated just with that script. So we could move to SGP4 issues

Mac Terminal says: 
LANG=de_DE.UTF-8

PyCharm says:
LC_CTYPE=de_DE.UTF-8

I had a conversation with the user with the division by zero error. As soon as he switched his language setting from German to English, the problem went away.

Another interesting point about: The error is visible only when running pytest with this script from the terminal. If I start the python interpreter and paste the script manually and let it run in the terminal, It succeeds without problems.

**Comment by brandon-rhodes** [comment]
When I run:
```
import sys
del sys.path[0]

from sgp4.api import Satrec, accelerated
print('Accelerated?', accelerated)
tle = [
    "NOAA 8",
    "1 13923U 83022A   20076.90417581  .00000005  00000-0  19448-4 0  9998",
    "2 13923  98.6122  63.2579 0016304  96.9736 263.3301 14.28696485924954",
]
sat = Satrec.twoline2rv(tle[1], tle[2])
print(sat.no_kozai)
```
— on my laptop, it always works, whether `LANG=de_DE.UTF-8` or `LC_CTYPE=de_DE.UTF-8`. Apparently Linux `sscanf()`, like Windows (from your earlier report), is stable even when the locale changes.

So I cannot test a solution myself. Could you have the affected user try installing `sgp4` through the following command?

```
pip install https://github.com/brandon-rhodes/python-sgp4/archive/test-locale-idea.zip
```

That will install a special branch I've just created that tries detecting the problem and working around it.

**Comment by mworion** [comment]
I have myself an environment, where I could reproduce this issue. Why I still don't know, but it it the same behavior like the users windows system.

If I use the official SGP4 release I get the problem, with your test version It seems to be OK. I get all informations populated.

Michel

**Comment by brandon-rhodes** [comment]
I have started a new 2.10 release that includes the locale improvement! The source and Mac and Windows wheels are already up. Unfortunately, the CI job to build the compiled Linux wheels is failing:

https://travis-ci.org/github/brandon-rhodes/python-sgp4/jobs/690188408

But for other platforms, the official release should now avoid the problem your user reported. Let me know if you receive further updates! Otherwise, let me know if the new version works for you and we can close the issue.

**Comment by brandon-rhodes** [comment]
(After a couple of re-tries, the Linux build proceeded and is now complete, so 2.10 should now be fully released!)

**Comment by mworion** [comment]
Thanks a lot.

Von meinem iPad gesendet

**Comment by brandon-rhodes** [comment]
Fun fact that I just remembered: I got to deal with this exactly same issue in 2009 with my old PyEphem library.

https://bugs.python.org/issue5125

And I thought I'd escaped because now with Skyfield all the code would be all-Python! Then performance tempted me, and I made `sgp4` C++ accelerated, and now I get to experience the past all over again. Alas. :)

**Comment by mworion** [comment]
That’s interesting. I like to say that physics can’t be bent. 

Michel

Von meinem iPad gesendet

**Comment by mworion** [comment]
Hi Brandon,

I have to admit, that my test environment was a little bit more robust than the user's one. The problem was still there with sgp4 2.10 / 2.11.  I build right now a windows virtual machine where I could reproduce this error to give you some hints.

I again tested your short script. It rund in that environment without error, when it is identical.
The difference to the usage in my app is, that there is one line in addition:

`import locale
    locale.setlocale(locale.LC_ALL, '')
`

If you add this to your test script, the no_kozai is 0. This happens when the region setting is Germany. If I change the region setting e.g. to UK, the script runs ok and shows a value !=0

Perhaps I make a fault myself using that setting. The intention is to set the locale setting to the setting of the OS.

Michel

**Comment by brandon-rhodes** [comment]
Well, drat.

The reason you will now be getting the problem is that, to avoid the danger and expense of changing the locale for every single call to `twoline2rv()`, I do a check at import time to see if I'm running on a system where locale is going to break `sscanf()`. It looks like this, in my `wrapper.cpp`:

```
    float f;
    sscanf("1,5", "%f", &f);
    switch_locale = (f == 1.5);
```

I guess I should instead do that check every single time `twoline2rv()` is called, because, as your example illustrates, it is possible for someone to change the locale later.

**Comment by brandon-rhodes** [comment]
@mworion — There! I've landed a possible fix. Could you try it out and let me know how it behaves?
```
pip install https://github.com/brandon-rhodes/python-sgp4/archive/master.zip
```
Thanks!

**Comment by mworion** [comment]
Thanks for the quick response. In my test setup it work. It will build directly for this user and let him test as well only to be sure we're finished with this issue.

Michel

**Comment by brandon-rhodes** [comment]
> Thanks for the quick response. In my test setup it works. It will build directly for this user and let him test as well only to be sure we're finished with this issue.

Thank you for asking for this additional check so that we learn whether we have solved their problem. I will hold off on doing a release until I hear from you.

**Comment by mworion** [comment]
..got a feedback from my user and he confirms the fix. So it should be done.
Michel
BTW: are you interested in some picture what I did with you extraordinary library?

**Comment by brandon-rhodes** [comment]
> BTW: are you interested in some picture what I did with you extraordinary library?

Yes, it is interesting to hear what folks are using the library for, thanks!

**Comment by brandon-rhodes** [comment]
And, version 2.12 has just been released with the new fix.

**Comment by mworion** [comment]
Brandon, thanks for the quick fixing and support. Closing the issue now.

I have to admit, that you and Skyfield were the reason for starting programming and app in astronomy in python. I saw your YouTube  Clean Architecture and that made me start.

Attached some images. It's an mount management tool, which exposes these satellite features and uses internally the most of the Skyfield Units, Time, etc. as reference.

![Bildschirmfoto 2020-05-28 um 19 28 07](https://user-images.githubusercontent.com/6632980/83180331-92f9e780-a123-11ea-835b-0d2e1f904609.png)
![Bildschirmfoto 2020-05-28 um 19 28 38](https://user-images.githubusercontent.com/6632980/83180338-955c4180-a123-11ea-8f1f-80c03713f720.png)

**Comment by brandon-rhodes** [comment]
Wow — that's an amazing looking application! My Python libraries keep me so busy with the numbers that I rarely have time to sit down and plot a visual result. The right-hand window is an amazing way to present several views of the same information, but in ways that highlight different aspects of the data!

Is this for telescope mounts, or radar / antenna mounts?

**Comment by mworion** [comment]
Thanks for the compliments! It is for telescope mounts. I started doing that for my environment. If there Is some time I'm doing astro photography.
