### ISSUE TITLE
Out of range produce invalid TLEs

### ISSUE THREAD

**Issue by astrojuanlu** [brandon-rhodes/python-sgp4#70]
The TLE FAQ specifies that:

> Fields 2.3, 2.4, 2.6, and 2.7 all have units of degrees and can range from 0 up to 360 degrees—field 2.3 (inclination) only goes up to 180 degrees.

However, if one creates a `Satrec` object with, say, `argpo=-1.90861`:

- `sgp4init` does not complain
- `rv2twoline` produces an invalid TLE!

For example:

```
1 99510U 20999B   20311.53996093  .00007856  00000-0  10000-4 0  9995  
2 99510  97.2675  23.7519 0007535 -109.3554278.9614 15.31068184    67 
```

Should python-sgp4 perform any sort of validation?

**Comment by astrojuanlu** [comment]
(Edit: typo, `argpo` is specified in radians, but I copy-pasted the value in degrees)

**Comment by brandon-rhodes** [comment]
Good question. Since the library is supposed to be a thin wrapper around the real C++ library, I am not sure it would be in the spirit of the library for `sgp4init()` to perform any checks that the underlying `sgp4init()` routine does not itself perform.

But that logic would not apply to any routines that aren't members of the underlying library — they could change without raising any surprises, since there is no C++ version of them. But first we should get clear on what routine we are talking about; I don't see a `rv2twoline()` function anywhere? Do you mean `export_tle()`?

**Comment by astrojuanlu** [comment]
Oh, I realized `rv2twoline` is only present in this fork by @enritoomey https://github.com/enritoomey/python-sgp4/blob/95b08fdfc8131bf6b7c81cd1211ba3eaa032349a/sgp4/io.py#L254 (:wave:). But yes, `export_tle` introduced in #59 (`sgp4>=2.6`) has this same problem:

```
>>> lines = """1 26975U 78066F   06174.85818871  .00000620  00000-0  10000-3 0  6809
... 2 26975  68.4714 236.1303 5602877 123.7484 302.5767  2.05657553 67521"""
>>> from sgp4.exporter import export_tle
>>> from sgp4.earth_gravity import wgs84
>>> from sgp4.io import twoline2rv
>>> sat = twoline2rv(*lines.splitlines(), wgs84)
>>> export_tle(sat)
('1 26975U 78066F   2006174.85818871  .00000620  00000-0  10000-3 0  6803', '2 26975  68.4714 236.1303 5602877 123.7484 302.5767  2.05657553 67521')
>>> sat.argp
sat.argpdot  sat.argpo    
>>> #sat.argpo = sat.argpo - 
>>> import numpy as np
>>> sat.argpo
2.159817024074951
>>> sat.argpo - 2 * np.pi
-4.123368283104636
>>> sat.argpo = sat.argpo - 2 * np.pi
>>> export_tle(sat)
('1 26975U 78066F   2006174.85818871  .00000620  00000-0  10000-3 0  6803', '2 26975  68.4714 236.1303 5602877 -236.2516 302.5767  2.05657553 67526')
```

Would you accept a pull request so that `export_tle` raises a `ValueError` or equivalent if any angle is out of range? We could think about performing other validations as well.

(Also, while studying this, I noticed #71)

**Comment by brandon-rhodes** [comment]
> Would you accept a pull request so that export_tle raises a ValueError or equivalent if any angle is out of range? We could think about performing other validations as well.

Yes! The routine was contributed back in April, and I have only ever touched one line of it myself. It would make sense to make it less dangerous by having it refuse to generate invalid TLEs by rejecting angles that are out of the range that the TLE can represent.
