### ISSUE TITLE
Include LICENSE file in pypi distribution

### ISSUE THREAD

**Issue by alhirzel** [brandon-rhodes/python-sgp4#74]
The [distribution on pypi](https://pypi.org/project/sgp4/) should include a `LICENSE` file. I need this to satisfy the requirement to install a copy of the license for this package using the [`PKGBUILD` I maintain for Arch Linux](https://aur.archlinux.org/packages/python-sgp4/). To wit, `namcap` currently gives [the following error](https://wiki.archlinux.org/index.php/Namcap#Licenses):

```
python-sgp4 E: Missing custom license directory (usr/share/licenses/python-sgp4)
```

See also, note on why this is motivated: https://wiki.archlinux.org/index.php/PKGBUILD#license

**Comment by brandon-rhodes** [comment]
I have just pushed a fix and confirmed that LICENSE now shows up in the .tar.gz file. I'll plan to make a release in the next few weeks that will include the fix!
