### ISSUE TITLE
Question about python3.9 support in wheels.

### ISSUE THREAD

**Issue by mworion** [brandon-rhodes/python-sgp4#75]
@brandon-rhodes,

as I heavily rely on skyfield and the linked sgp4 package and I would like to move the on top build applications to support python3.9. Is there any planning, when the sgp4 distro also brings the precompiled packages with it?

many thanks for this great packages.
Michel

**Comment by brandon-rhodes** [comment]
Wow, Python 3.9 is out! Yes, let’s plan on adding it to the CI files and including it in the next release. Thanks for pointing out that it’s time to support a new Python version.

**Comment by brandon-rhodes** [comment]
I’ll plan to do a release sometime this week, and hopefully the cibuildwheel tool does the right thing and builds for 3.9 (I don't see an option to select it explicitly?).

**Comment by brandon-rhodes** [comment]
The new release indeed appears to include wheels for 3.9! Let me know if you have any problem installing them.

https://pypi.org/project/sgp4/#files
