### ISSUE TITLE
Failure running some tests in a different time zone 

### ISSUE THREAD

**Issue by pleira** [brandon-rhodes/python-sgp4#8]
When running tests in a different time zone (I am in CET), some tests fail:

Failed tests:   testNextSatPass(uk.me.g4dpz.satellite.PassPredictorTest): expected:<2009-01-05T0[4:28:10+00]00> but was:<2009-01-05T0[5:28:10+01]00>
  testNextSatPassWithWindBack(uk.me.g4dpz.satellite.PassPredictorTest): expected:<2009-01-05T0[4:28:10+00]00> but was:<2009-01-05T0[5:28:10+01]00>
  correctToStringResult(uk.me.g4dpz.satellite.PassPredictorTest): expected:<...5, 2009(..)
  poleIsPassed(uk.me.g4dpz.satellite.PassPredictorTest): expected:<2009-01-05T0[7:42:45+00]00, north> but was:<2009-01-05T0[8:42:45+01]00, north>

Tests run: 32, Failures: 4, Errors: 0, Skipped: 0

**Comment by brandon-rhodes** [comment]
(Sorry for taking so long to answer! Not until PyCon 2016 finished this week have I been able to start digging through my list of GitHub issues.)

Those tests are, alas, not part of sgp4’s source code, and I don’t think that sgp4 itself uses time zones. I expect that you will have to find the maintainer of the `uk.me.g4dpz` project to learn why the tests fail in your time zone. Good luck, I hope you can get the issue resolved!
