### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by brandon-rhodes** [brandon-rhodes/python-sgp4#84]
Potential contributors need feedback from CI test builds, but with Travis CI at its end-of-life, build results are no longer being posted back to Pull Requests.

1. Developers can run `tox` locally, if they `pip install tox` first, to at least see whether the tests pass locally.
2. And longer-term, a volunteer will need to replace the project `.travis.yml` with the GitHub Actions equivalent to make CI results available again.

Anyone interested in tackling the project can comment here on this issue expressing their interest. In the meantime, contributors should use `tox` locally.

**Comment by mworion** [comment]
@brandon-rhodes 
If you don't mind, I'll give it a try during the next 1 or two weeks. I never did use travis, but I do use GitHub actions in my project. So I will find out. My guess is that you would like to run the tests each commit and each PR.
Michel

**Comment by brandon-rhodes** [comment]
@mworion — Thank you for the offer! I'll assign you this issue officially. Yes, commits and PRs. Like the `tox` setup and the current Travis CI setup, the project will need both at least a Python 2.7 run and a Python 3.something run where the latter makes sure that the project compiles under Python 3 instead of falling back to the Python version. (See `setup.py` which might detect when it's on Travis?)

I'll watch the issue over the next several weeks in case you have questions.

**Comment by mworion** [comment]
@brandon-rhodes:
linting with pyflakes is running on all demanded  python versions
sgp4/tests are running on all demanded  python versions
testing build package done as well

some questions:
- do I have to build and test on ppc64le as well? (difficult)
- need to test on different os (windows, Ubuntu, macOS)? (easy)
- what about having the the speedup version. How could I see if the c code is running ? (no clue so far)
- Building wheels afterwards (or separate action) (duable)
- Upload possibility to PyPi ? (easy step, your have to configure)

**Comment by brandon-rhodes** [comment]
> do I have to build and test on ppc64le as well? (difficult)

Don't spend time on it, no. If there are third parties for whom that build is crucial, they can run as part of their packaging suite, or maybe will be interested in contributing the work towards having that platform in GitHub Actions.

> need to test on different os (windows, Ubuntu, macOS)? (easy)

Sure, let's go for it. It's more compute on each commit, but development is pretty much done at this point, so I'm not anticipating high volume — and if folks are going to break things under other OS's, it lets them discover that rather than my not learning about it til release time :)

> what about having the the speedup version. How could I see if the c code is running ? (no clue so far)

Add a quick `print` statement in the CI commands that shows the value of `sgp4.api.accelerated`. It should be `True` if the compilation worked.

> Building wheels afterwards (or separate action) (duable)

If you'd like to suggest how that would look, that would be great! You could add it as a comment and I could uncomment it over on the `release` branch, would be one approach; but that's not as crucial right now as getting the master branch tested again, since Travis CI is still fine for releases (since only I see the results; so nothing needs to be posted back for other developers on GitHub to see).

> Upload possibility to PyPi ? (easy step, your have to configure)

If you're interested in tossing in the code, I could try uncommenting and using it over on the release branch the next time we come out with a new version.

Thanks, and let me know if you have more questions!

**Comment by mworion** [comment]
@brandon-rhodes: 
Progressing with automation with different OS. From my point of view, windows was
never tested as well as the 32bit accelerated version. Both are now part of the tests.

We have to take care about the errors arising due to the extended tests (further
down more detailed explanations and where to look for the tests)):

1) string default coding (python 2.7 vs. 3.x  ascii vs. UTF), which arises on
windows tests
-> solutions: adopt test or remove windows tests

2) difference carriage return + linefeed  vs. linefeed only for windows vs. non
windows os.
-> solutions: adopt test or remove windows tests

3) precision of float in 32 bit tests accelerated
-> solution: use compiler option "-ffloat-store", which seems to solve the problem,
at least the tests run without errors.

And I have some more more questions and recommendations:
- Is there actually a need to build aarch64 wheels in short time? There will be a solution to have the same architecture supported as on travis, but the maintainer need some more time. But as travis sunsets there is a clear target for it.
- I would like to limit the tests to official active python versions: 2.7, 3.6 - 3.9. Any thought about this ?
- In the package I see different manylinux (1, 2010, 2014) binaries. Is there any need for supporting more than manylinux2014 ?





Now the details for test errors 1) and 2), for 3) I would put it to the compiler issue.

1) Windows 2.7 vs. 3.x: default string encoding

Related to unicode default in python 3.x and ascii in python 2.7 for strings.
The three tests ask for a unicode string, but gets ascii. I do not know, why this is
not an issue if I use ubuntu as underlying os, but in windows it pops up.

```
ERROR: test_legacy_against_tcppver (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 532, in test_legacy_against_tcppver
    run_satellite_against_tcppver(make_legacy_satellite, run_legacy_sgp4, errs)
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 584, in run_satellite_against_tcppver
    % (lineno, expected_line, actual_line))
ValueError: Line 1 of output does not match:
Expected: u'5 xx\r\n'
Got back: '5 xx\n'

ERROR: test_satrec_against_tcppver_using_julian_dates (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 498, in test_satrec_against_tcppver_using_julian_dates
    run_satellite_against_tcppver(Satrec.twoline2rv, invoke, [1,1,6,6,4,3,6])
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 584, in run_satellite_against_tcppver
    % (lineno, expected_line, actual_line))
ValueError: Line 1 of output does not match:
Expected: u'5 xx\r\n'
Got back: '5 xx\n'

ERROR: test_satrec_against_tcppver_using_tsince (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 506, in test_satrec_against_tcppver_using_tsince
    run_satellite_against_tcppver(Satrec.twoline2rv, invoke, [1,1,6,6,4,3,6])
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 584, in run_satellite_against_tcppver
    % (lineno, expected_line, actual_line))
ValueError: Line 1 of output does not match:
Expected: u'5 xx\r\n'
Got back: '5 xx\n'
```

2) Windows handling carriage return and linefeed for string lines:

Same tests as above, handling carriage return and line feed in windows. Windows only
new line:

```
ERROR: test_legacy_against_tcppver (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 532, in test_legacy_against_tcppver
    run_satellite_against_tcppver(make_legacy_satellite, run_legacy_sgp4, errs)
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 579, in run_satellite_against_tcppver
    raise ValueError(
ValueError: Line 1 of output does not match:
Expected: '5 xx\r\n'
Got back: '5 xx\n'

ERROR: test_satrec_against_tcppver_using_julian_dates (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 498, in test_satrec_against_tcppver_using_julian_dates
    run_satellite_against_tcppver(Satrec.twoline2rv, invoke, [1,1,6,6,4,3,6])
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 579, in run_satellite_against_tcppver
    raise ValueError(
ValueError: Line 1 of output does not match:
Expected: '5 xx\r\n'
Got back: '5 xx\n'

ERROR: test_satrec_against_tcppver_using_tsince (__main__.TestFunctions)
Traceback (most recent call last):
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 506, in test_satrec_against_tcppver_using_tsince
    run_satellite_against_tcppver(Satrec.twoline2rv, invoke, [1,1,6,6,4,3,6])
  File "D:\a\python-sgp4\python-sgp4\sgp4\tests.py", line 579, in run_satellite_against_tcppver
    raise ValueError(
ValueError: Line 1 of output does not match:
Expected: '5 xx\r\n'
Got back: '5 xx\n'

```

**Comment by brandon-rhodes** [comment]
> @brandon-rhodes: Progressing with automation with different OS. From my point of view, windows was never tested as well as the 32bit accelerated version. Both are now part of the tests.

Amazing! Yes, previously only the “release” build focused on many OS’s. Now that the main build will also be able to test those OS’s, will that make the main build and the release build more similar than they were before?

We have to take care about the errors arising due to the extended tests (further
down more detailed explanations and where to look for the tests)):

string default coding (python 2.7 vs. 3.x ascii vs. UTF), which arises on
windows tests
-> solutions: adopt test or remove windows tests

difference carriage return + linefeed vs. linefeed only for windows vs. non
windows os.
-> solutions: adopt test or remove windows tests

I changed 561 in test.py to:

similar = (actual_line.replace('\r', '') == expected_line.replace('\r', ''))
which should cover both, because in tests on windows comparison accepts both string codings

And I have some more more questions and recommendations:

> Is there actually a need to build aarch64 wheels in short time? There will be a solution to have the same architecture supported as on travis, but the maintainer need some more time. But as travis sunsets there is a clear target for it.

I am not sure, I do not have data on which versions of the binary wheels are in heavy use. But “cibuildwheel” builds that architecture automatically, I think, so it’s not something we need to make a decision on?

> I would like to limit the tests to official active python versions: 2.7, 3.6 - 3.9. Any thought about this?

I do not see a reason to test against Python 3.5 or earlier 3’s, as I have never heard of anyone stuck on very early Python 3 versions. It would be nice to keep testing under 2.6, since some users are probably still stuck there, but we can always decide — if 2.6 testing is hard to arrange — that we will only test 2.6 locally best-effort, and wait for user reports to let us know if we’ve broken something. (Which has the advantage that it would be driven by real-life 2.6 users rather than a guess about whether they still exist.)

> In the package I see different manylinux (1, 2010, 2014) binaries. Is there any need for supporting more than manylinux2014 ?

I have always allowed “cibuildwheel” to build its full suite of packages, because I have assumed that its maintainer knows far more than I do about what package versions are in use. If we build them all, we support the maximum number of users, so I am not sure there would be a reason to have “cibuildwheel” turn some versions off that it wants to build.

> Related to unicode default in python 3.x and ascii in python 2.7 for strings. The three tests ask for a unicode string, but gets ascii. I do not know, why this is not an issue if I use ubuntu as underlying os, but in windows it pops up.

Note that the problem in the test you are quoting is the mismatch in line endings, not the str/unicode difference. In Python 2 it doesn’t mind saying unicode equals a bytestring:
```
>>> 'abc' == u'abc'
True
```
You might want to do something like:
```
    data = get_data(__name__, 'tcppver.out')
    data = data.replace(b'\r', b'')
    tcppver_lines = data.decode('ascii').splitlines(True)
```
I really should rewrite that whole test section to be a bit less convoluted (so maybe it writes out the whole output file then does a full diff?), but haven’t had time to tackle it. For now we can just do tweaks like the one I just suggested to try to get the existing code working.

(Did I answer all of your questions? Just let me know which ones I accidentally didn’t answer!)

**Comment by mworion** [comment]
Actually I really don't distinguish between maser and release branch. The only difference is that on release I upload the package to PyPI automatically when all tests go through. You could also trigger that with a tag or something else.

aarch64 is currently not supported from cibuildwheels on GitHub , only on Travis. The maintainer is working on a solution to integrate is as well, but I also have a separate docker solution who could build arch on top separately if needed. The main path for me would be to wait for the integration in cibuildwheel and the just switch it on.

I could add as much as cibuildwheel could support, should be no problem. It's only runtime on Github (actually 15 min for all tests runs and all builds).

I also remove the manylinux restrictions.

I change the test and remove the '\r'.

There is the chance to write automatically on release commit the release in gut hub and add a tag for it (would be some work to do). For all other things (depending on the decision about the compiler flag) I could provide a first PR for you to check.

**Comment by brandon-rhodes** [comment]
> aarch64 is currently not supported from cibuildwheels on GitHub , only on Travis.

Ah, thanks for the clarification! Then I am happy to leave it unsupported for now; and if users complain after the next release then we can reconsider.

> actually 15 min for all tests runs and all builds

Alas that it has to burn so much CPU! Locally with tox I'm able to verify both Python 2 and Python 3 in only 7.11s. But I guess even just spinning up a Windows box is time-consuming.

> There is the chance to write automatically on release commit the release in gut hub and add a tag for it (would be some work to do).

I prefer to do tagging locally, so I am happy to have you leave that off and not spend time on it. I look forward to seeing the PR!

**Comment by mworion** [comment]
We permutate all things for the tests which are possible, that's really much. 8 python versions on three operating systems on 2 architectures accelerated and "pure" and btw. build all the wheels and the distro. That might be a fair deal.

I have to admit: python 2.6 is not supported for GitHub Actions.

**Comment by brandon-rhodes** [comment]
That's a lot of combinations, yes! I guess contributors will just have to be patient and wait to see their test results :)

**Comment by mworion** [comment]
I kept the actions now clean und straight forward on the red line GitHub supports.
I terms of speedup I build the wheels and accelerated tests (expensive) only when standard python tests (cheap) were OK. There are chances, depending how much PR or changes you expect.
I submit the PR with some work left over: config the upload secret token.

**Comment by brandon-rhodes** [comment]
Thanks so much! I'll go take a look.

**Comment by brandon-rhodes** [comment]
When I visit the Actions dashboard, I now see successful builds:

https://github.com/brandon-rhodes/python-sgp4/actions

So I am going to close this issue as a success. Thanks so much for putting that pull request together!
