### ISSUE TITLE
High Eccentricity Breaks Predictor?

### ISSUE THREAD

**Issue by meawoppl** [brandon-rhodes/python-sgp4#92]
In the quite recently released `stations.txt` the following entry appears:
```
2021-048B               
1 48832U 21048B   21155.73590201  .99940241  10591-4  34345-1 0  9999
2 48832  51.7067  44.7823 0077910 180.2116 179.8584 16.16912723   150
```

The eccentricity is notably high for this object, but it is a valid value.
When using the following skyfield code:

```
topocentric = (satellite - self.position).at(tt)
result = topocentric.altaz()
ele, az, _ = result

if math.isnan(ele.degrees):
    print(ele, az)
    print(topocentric.message)  # <--- Message from this line
    print(satellite)
    print(satellite.model)
```
I get the message `mean eccentricity is outside the range 0.0 to 1.0`, which isn't true.

I don't expect accurate predictions for this object, but the parameter is in the valid range.... so maybe there needs to be a tweak to the error message?

**Comment by brandon-rhodes** [comment]
Could you by any chance provide a full working example script? I think the next step will be printing out the mean parameters that the SGP4 propagator computed for the moment in time that you're asking about. They should be available on `satellite.model`:

https://pypi.org/project/sgp4/#attributes

**Comment by meawoppl** [comment]
Let me make a little stand alone repro. It seems to spend a fair bit of time in the prediction code before giving up as well, so this is my day's focus

**Comment by meawoppl** [comment]
Alright, here we are:
```
import math
import datetime

from skyfield.api import wgs84
from skyfield.sgp4lib import EarthSatellite
from skyfield import api

ts = api.load.timescale()


dt = datetime.datetime(2021, 6, 8, 10, 11, 33, 553225, tzinfo=datetime.timezone.utc)
tt = ts.utc(dt)

position = wgs84.latlon(37.7749, 122.4194, 15)

line0, line1, line2 = """2021-048B               
1 48832U 21048B   21155.73590201  .99940241  10591-4  34345-1 0  9999
2 48832  51.7067  44.7823 0077910 180.2116 179.8584 16.16912723   150""".split("\n")

sat = EarthSatellite(line1, line2, line0, ts)

topocentric = (sat - position).at(tt)
result = topocentric.altaz()
ele, az, _ = result

if math.isnan(ele.degrees):
    print(topocentric.message)
    for name in dir(sat.model):
        if not name.startswith("_"):
            print(name, ":", getattr(sat.model, name))
```

And corresponding output:
```
(base) meawoppl@monolith:~/repos/telescope-sim/sim$ python demo.py 
mean eccentricity is outside the range 0.0 to 1.0
Om : 0.7815985816158566
a : 1.0358189849198836
alta : 0.04388905063139448
altp : 0.027748919208372858
am : 1.0358189849198836
argpdot : 4.902483674750899e-05
argpo : 3.145285770287013
bstar : 0.034345
classification : U
ecco : 0.007791
elnum : 999
em : 0.007791
ephtype : 0
epochdays : 155.73590201
epochyr : 21
error : 65646
gsto : 2.7630048584990945
im : 0.902452160340952
inclo : 0.902452160340952
intldesg : 21048B
j2 : 0.001082616
j3 : -2.53881e-06
j3oj2 : -0.002345069720011528
j4 : -1.65597e-06
jdsatepoch : 2459369.5
jdsatepochF : 0.73590201
mdot : 0.07055113590905955
method : n
mm : -3.144064039810617
mo : 3.139121267368969
mu : 398600.8
nddot : 2.2285858058294688e-14
ndot : 3.028274758136511e-06
nm : 0.0705430076864778
no : 0.07055112683434261
no_kozai : 0.07055112683434261
nodedot : -6.620908870557843e-05
nodeo : 0.7815985816158566
om : 3.145285770287013
operationmode : i
radiusearthkm : 6378.135
revnum : 15
satnum : 48832
sgp4 : <built-in method sgp4 of Satrec object at 0x55d5e0833640>
sgp4_array : <bound method Satrec.sgp4_array of <sgp4.wrapper.Satrec object at 0x55d5e0833640>>
sgp4_tsince : <built-in method sgp4_tsince of Satrec object at 0x55d5e0833640>
sgp4init : <built-in method sgp4init of Satrec object at 0x55d5e0833640>
t : 5311.8603260166665
tumin : 13.446839696959309
twoline2rv : <built-in method twoline2rv of type object at 0x55d5e07c6130>
xke : 0.07436691613317342
```

I am not familiar with the internals enough to interperate this all, but lmk if I can help with a PR/debug of some variety...

**Comment by brandon-rhodes** [comment]
Searching the SGP4 code, it looks like this is the only place where the error code 1 can be set:

https://github.com/brandon-rhodes/python-sgp4/blob/2607117f18cc42b8f4011a43a96686fbccbd265d/extension/SGP4.cpp#L1853

The condition is:

```
		if ((em >= 1.0) || (em < -0.001)/* || (am < 0.95)*/)
		{
			//         printf("# error em %f\n", em);
			satrec.error = 1;
			// sgp4fix to return if there is an error in eccentricity
			return false;
		}
```

It looks like the `.em` value in the struct does not, alas, get set if this error is thrown, so there's no way for you to recover the actual value without editing the above code to turn on the `printf()` or somehow otherwise save away the value.

But it looks like however the eccentricity evolves, SGP4 thinks that it's an invalid and unworkable value at the date and time you're asking about.

Since Skyfield's goal here is simply to run SGP4 without making any modification to its behavior (so that it matches all other satellite propagation routines), my guess is that there's nothing further we can do, and that you might want to ask the routine's authors or other satellite experts about your satellite's behavior and why the official routine won't give you a valid propagation?

**Comment by meawoppl** [comment]
All good. I got a good answer here:
https://twitter.com/planet4589/status/1402337768769048578?s=20
Sounds like this is the "expected" behavior even if unhelpful...

Thanks for looking and maintaining this all!

**Comment by brandon-rhodes** [comment]
I'm glad someone offered a plausible explanation for why this might be expected behavior from the model! Let me know if you hear of any improvements to SGP4 which might change its behavior here in the future.
