### ISSUE TITLE
Periodic Orbital Energy

### ISSUE THREAD

**Issue by harrison-caudill** [brandon-rhodes/python-sgp4#93]
As a quick sanity-check of an orbital simulator I've been writing, I produced a graph of time vs orbital energy so I could make sure I was properly conveying things like the BStar drag term.  When I did that, I found that the energy (T+V) would vary throughout the orbit, and the mean value would decrease as expected from drag.

I retried with a TLE I grabbed from Celestrak, then finally tried again copying/pasting the example code from the documentation all with the same results.  I also tried setting the bstar term to 0, which eliminated the decay of the average value but did nothing for the periodic nature of it.

I then replaced the SGP4 propagator with a keplerian propagator as a positive control and found that T+V remained constant throughout the orbit.

I'm sure I'm missing something obvious here, but I don't see it.  When I constructed poliastro orbit objects using the state vectors returned, I would see periodic variations in the expected apoapsis of the orbit with the same decay over time of the average value.  Those variations in expected apopsis were around 15km, so there's no way that could ever have passed a unit test (hence me thinking I'm missing something obvious).

I tried building from the latest source code as well as installing the latest version from pypi.

```python
def __propagate():
        retval = []
        s = '1 25544U 98067A   19343.69339541  .00001764  00000-0  38792-4 0  9991'
        t = '2 25544  51.6439 211.2001 0007417  17.6667  85.6398 15.50103472202482'
        satellite = sgp4.api.Satrec.twoline2rv(s, t)

        dt = 10*u.min
        d_fr = dt.to('d').value
        jd, fr = 2458827, 0.362605
        for i in range(n):
            e, r, v = satellite.sgp4(jd, fr)
            fr += (d_fr/2)
            retval.append((r, v,))

def __plot():

        x = np.arange(0, dt.value*len(states), dt.value)
        y_raw = []
        M = poliastro.constants.M_earth
        G = astropy.constants.G
        for i in range(len(x)):
            rr, vv, = states[i]
            rr = rr.value
            vv = vv.value
            E = .5*np.dot(vv, vv) - G.value*M.value/np.dot(rr, rr)**.5
            y_raw.append(E)

        fig = plt.figure()
        fig.suptitle('SGP4 Propagation Altitude vs Time')
        ax = fig.add_subplot(1, 1, 1)
        ax.plot(x, y_raw, label='Orbital Energy')
        ax.legend()
        ax.set_xlabel('Time since epoch (s)')
        ax.set_ylabel('Specific Orbital Energy (J/kg)')
        fig.savefig("/some/where.png", transparent=False)
```

**Comment by brandon-rhodes** [comment]
Did you close the issue because you worked out the answer? I'd be interested to hear what your conclusion was.

**Comment by harrison-caudill** [comment]
Hey Brandon,

I closed it because I'm reasonably certain it was a PEBKAC issue.  I
also realized that your email address was actually available.

I had (erroneously, it seems) assumed that Poliastro
(https://docs.poliastro.space/en/stable/index.html) would deal the
oblateness of the earth when computing orbital parameters.  I did some
source diving and realized that I had erred -- it assumes an ideal
keplerian orbit in the poliastro.twobody.orbit.Orbit class without
accounting for J2.  I also erred when I was computing the
gravitational potential energy of the satellite, and not taking the
same into account.  I'm also guessing that I erred in my intuition
about how much of a difference J2 makes.

My hypothesis is three-fold:
 * When I was computing (T+V)/m as 1/2 * v dot v - GM/|r|, my
potential energy was wrong because it assumed a point-mass.  As such,
my computation of orbit energy would naturally be incorrect and also
periodic with T_energy=T_orbit

 * Poliastro orbit objects similarly do not account for oblateness,
which would also result in a predicted apogee/perigee that varies
periodically again with T_apogee = T_orbit if the orbit object is
constructed from state vectors after propagating with SGP4.  My
observations were of a ~20km difference in predicted apogee on a
500ish km orbit

 * My intuition (if that's even the word for it) about the magnitude
of the J2 impact on the orbit was poor.

Since my objective is to produce estimates for lambert's problem, my
likely next step will be to:

 1. Use the izzo algorithm from poliastro to produce an approximation

 2. Time propagate both spacecraft over the time of flight (tof) using SGP4

 3. Determine the vector between the two.

 4. Add a linear delta to the original burn vector to account for the
difference between izzo and SGP4

 5. Lather-rinse-repeat as desired.

I appreciate the quick response, and I'll try to reciprocate (though
the 1-year-old makes that difficult at times).  Happy to help out the
project if I can.

Cheers,
Harrison


On Sun, Jun 27, 2021 at 9:28 AM Brandon Rhodes ***@***.***> wrote:
>
> Did you close the issue because you worked out the answer? I'd be interested to hear what your conclusion was.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Harrison Caudill
Founder
Orbital Security Alliance
+1 559.464.5387
***@***.***

**Comment by brandon-rhodes** [comment]
Thanks for the details! If you want to dive deeper into SGP4, there is — besides its source, of course — quite a few parameters exposed on the `.model` of a Skyfield satellite, which is a raw `sgp4` object. There's even a parameter named `j2`:

https://pypi.org/project/sgp4/

If you figured out how the `j2` parameter is used to adjust the orbit (I myself have not looked at it in detail), then by printing it you might get a sense for how big an effect it has on the result.
