### ISSUE TITLE
Bug in exporter() method line 52

### ISSUE THREAD

**Issue by mworion** [brandon-rhodes/python-sgp4#94]
I run over a problem when exporting a long list of sats to a text file. In detail it was BEIDOU-3 M23, but as values change this might be already different by now

The problem when SGP4 model parameters the bstar value is 
`-66561+1`
in original TLE file, the import routine does calc a value of
`-6.6561`
In my opinion the correct value. When exporting the model data to a TLE file via exporter in line 52, the result is
`-66561e+01`
which is obviously wrong. My suspicion is that unlike negative exponents where the replacement is "e-0" to "-", the replacement for positive exponents is "e+00" with "+0". In my opinion it should be
`replace("e+0", "+")`
which brings the correct result of
`'-66561+1 '`

Michel

Here the TLE values (line0, line1, line2):
`
    tle = ["BEIDOU-3 M23",
           "1 44542U 19061A   21180.78220369 -.00000015  00000-0 -66561+1 0  9997",
           "2 44542  54.7025 244.1098 0007981 318.8601 283.5781  1.86231125 12011"]
`

**Comment by brandon-rhodes** [comment]
> "1 44542U 19061A 21180.78220369 -.00000015 00000-0 -66561+1 0 9997"

At least the way you've punctuated and spaced it, I don't think that's a valid TLE line? At least, I can't get the library to accept it. Could you try pasting again, and check whether whitespace is preserved? Thanks!

**Comment by mworion** [comment]
Yes, might be a copy error. Here the extract from the downloaded file:
```
BEIDOU-3 M23            
1 44542U 19061A   21180.78220369 -.00000015  00000-0 -66561+1 0  9997
2 44542  54.7025 244.1098 0007981 318.8601 283.5781  1.86231125 12011
```

**Comment by brandon-rhodes** [comment]
Thanks for letting me know about the problem, and for supplying the complete TLE lines!

The export routine is contributed code, so I'm not entirely familiar with it, but I've put together a quick patch a1eba42493807c51af6e83ca967afbca9bf4bf7d to try to address its problem with positive exponents when exporting new TLE lines.

If you have a compiler installed and could try it out before I release a new version of SGP4, you can install the development version with:

    pip install -U https://github.com/brandon-rhodes/python-sgp4/archive/master.zip

**Comment by mworion** [comment]
@brandon-rhodes,
thanks for the quick fix. But I have to admit that I work on Mac and still struggling with compile versions in relation to python packages. I have Xcode installed, but the pip install does not run it automatically. So I'm at this point helpless.
My test for checking TLE in/out handling still throws this error as it uses the compiled version, which has not the fix in.
Are there any chances to force SGP4 to use the python only version?
Anyway, your implementation makes sensor for me as my proposal replaced a part and you added the missing corner case.
As I run with my app many exports since months, this was the first event showing the issue. So it will be very seldom.
Michel

**Comment by mworion** [comment]
@brandon-rhodes ,
everything is fine. We probably both made a mistake about the thinking of the compiled version and I myself in addition a mistake installing SGP4 from master correctly. I removed SGP4 and reinstalled from master. My test works now without error. The exporter exists only in python, so test went green without even removing the wrapper.py
Michel

**Comment by brandon-rhodes** [comment]
> The exporter exists only in python

Oh! Yes, that makes sense. :)

I'll try to get a release out tomorrow!
