### ISSUE TITLE
OMM Feature request: expose more OMM fields in Satrec

### ISSUE THREAD

**Issue by jester-xbmc** [brandon-rhodes/python-sgp4#96]
Hi again :)

As we will slowly move to OMM, i'm trying to get my tool ported to OMM, it would help if more (all?) fields read from an OMM file would be accessibly via Satrec

Example, object_name (aka its name or line 0 in a TLE/3LE file) is not exposed

Thanks !

**Comment by brandon-rhodes** [comment]
Alas, the official C++ code offers no mechanism for saving the name:

https://github.com/brandon-rhodes/python-sgp4/blob/7f3319534852791d60e34efc1b83340cf4a7fc76/extension/SGP4.h#L68

I suppose you could make your own subclass of Satrec that adds a Python-level attribute for the name, though. What does the loop look like that you're using to read in satellites? If you could share what your loader code looks like, I'll be happy to suggest how you might store the name on a custom satellite object, and if it works for you we could add it to the documentation for other people to use!

**Comment by jester-xbmc** [comment]
I'm actually "just" using the spacetrack module to download an OMM and TLE files to disk, read the file using the below and then using your skyfield module load.tle feature just to get the name as satellite.name, and epoch as satellite.epoch.utc_strftime()

```
with open('omm_latest.csv', 'r') as fp:
        fields = next(omm.parse_csv(fp))
satomm = Satrec()
omm.initialize(satomm, fields)

```
If this all can be done from SPG4 it would clean things up :)

**Comment by jester-xbmc** [comment]
As said, I'm an python n00b, so I see with the above code from your example,you have all the data I need in the "fields" variable

{'CCSDS_OMM_VERS': '2.0', 'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API', 'CREATION_DATE': '2021-07-26T04:56:10', 'ORIGINATOR': '18 SPCS', 'OBJECT_NAME': 'ISS (NAUKA)', 'OBJECT_ID': '2021-066A', 'CENTER_NAME': 'EARTH', 'REF_FRAME': 'TEME', 'TIME_SYSTEM': 'UTC', 'MEAN_ELEMENT_THEORY': 'SGP4', 'EPOCH': '2021-07-26T04:13:34.905216', 'MEAN_MOTION': '15.66150957', 'ECCENTRICITY': '0.0053271', 'INCLINATION': '51.6412', 'RA_OF_ASC_NODE': '150.2786', 'ARG_OF_PERICENTER': '115.6608', 'MEAN_ANOMALY': '17.1454', 'EPHEMERIS_TYPE': '0', 'CLASSIFICATION_TYPE': 'U', 'NORAD_CAT_ID': '49044', 'ELEMENT_SET_NO': '999', 'REV_AT_EPOCH': '72', 'BSTAR': '0.000073864', 'MEAN_MOTION_DOT': '0.00007736', 'MEAN_MOTION_DDOT': '0', 'TLE_LINE0': '0 ISS (NAUKA)', 'TLE_LINE1': '1 49044U 21066A   21207.17609844  .00007736  00000-0  73864-4 0  9992', 'TLE_LINE2': '2 49044  51.6412 150.2786 0053271 115.6608  17.1454 15.66150957   722', 'SEMIMAJOR_AXIS': '6748.068', 'PERIOD': '91.945', 'APOAPSIS': '405.880', 'PERIAPSIS': '333.985', 'OBJECT_TYPE': 'PAYLOAD', 'DECAYED': '0'}` 

So now I need to figure out code to read all these into separate variables using the above names and values so I can call them in my python program

**Comment by brandon-rhodes** [comment]
Did you close the issue because you figured out how to store the satellite name, and so you've been able to move on? I wanted to check in case you'd clicked the button by accident.

**Comment by jester-xbmc** [comment]
Thanks for checking, indeed I closed as I feel that keeping an issue open just to ask silly questions based on my lack of python knowledge is wasting people's (yours mainly) time :)

I used (fields["OBJECT_NAME"]) to display it in the end after importing an OMM file using your omm.parse_csv function (very handy, thanks !)
